### ISSUE TITLE
Reqroll.MsTest version needs updating in ReqnrollQuickstart.Specs.csproj

### ISSUE THREAD

**Issue by radiosity** [reqnroll/Quickstart#1]
Currently the solution targets a pre-release version:

`<PackageReference Include="Reqnroll.MsTest" Version="1.0.0-pre20240125-60" />`

This results in a compiler error CS0246: The type or namespace name 'DataTable' could not be found (are you missing a using directive or an assembly reference?)

Updating to:

`<PackageReference Include="Reqnroll.MsTest" Version="1.0.1" />`

Clears this error and correctly runs the test.

**Comment by gasparnagy** [comment]
Ups. Do you have time to make a quick PR for this please? I could only do it tomorrow.

**Comment by radiosity** [comment]
I will try to do one tonight - my sincere apologies for not including one, I can't do so from this dev environment.

**Comment by gasparnagy** [comment]
Fixed by #2
