### ISSUE TITLE
Had difficulty to compile 'completed' branch

### ISSUE THREAD

**Issue by chunxingshen** [reqnroll/Quickstart#3]
I initially had difficulty to compile 'completed' branch, and has to make a minor change of changing DataTable to table to get it work. 

![image](https://github.com/reqnroll/Quickstart/assets/120861438/f46b6b35-07ec-4e7e-ac17-56df962e7d29)

**Comment by gasparnagy** [comment]
fixed. (had to rebase the completed branch on main)
