### ISSUE TITLE
How to set priority for scenarios in the feature file

### ISSUE THREAD

**Issue by pritesh848** [reqnroll/Quickstart#4]
I have a feature with multiple scenarios and each scenario is linked to each others so I need to give priority to each scenario,  any ways to set priority in reqnroll with xunit

@priority:1
Scenario: First scenario to run
  ...

@priority:2
Scenario: Second scenario to run
  ...

if I add this @priority:1 or @priority1 nothing is happening it was taking scenario order of reverse alphanumeric of scenario first character

**Comment by gasparnagy** [comment]
moved to https://github.com/orgs/reqnroll/discussions/289
